apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../../base
images:
  - name: k8s.gcr.io/provider-aws/aws-ebs-csi-driver
    newName: 048912060910.dkr.ecr.cn-northwest-1.amazonaws.com.cn/gcr/google_containers/provider-aws/aws-ebs-csi-driver
    newTag: v0.8.0
  - name: quay.io/k8scsi/csi-provisioner
    newName: 048912060910.dkr.ecr.cn-northwest-1.amazonaws.com.cn/quay/k8scsi/csi-provisioner
    newTag: v1.5.0
  - name: quay.io/k8scsi/csi-attacher
    newName: 048912060910.dkr.ecr.cn-northwest-1.amazonaws.com.cn/quay/k8scsi/csi-attacher
    newTag: v2.2.0
  - name: quay.io/k8scsi/livenessprobe
    newName: 048912060910.dkr.ecr.cn-northwest-1.amazonaws.com.cn/quay/k8scsi/livenessprobe
    newTag: v2.1.0
  - name: quay.io/k8scsi/csi-node-driver-registrar
    newName: 048912060910.dkr.ecr.cn-northwest-1.amazonaws.com.cn/quay/k8scsi/csi-node-driver-registrar
    newTag: v1.3.0

